In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data',arr)

In [6]:
arr2 = np.load('data.npy')

In [7]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 = np.arange(20)

In [9]:
np.savez('arrays',a=arr,b=arr1)

In [10]:
arrays = np.load('arrays.npz')

In [11]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.savez_compressed('array_comp.npz',a=arr,b=arr1)