In [1]:
import numpy as np

In [2]:
data1 = [1,2,3,5,8,9]
arr1 = np.array(data1)#array 1 ni bradi

In [3]:
arr1

array([1, 2, 3, 5, 8, 9])

In [4]:
data2 = (4, 9, 8, 3, 5)#tikul
arra2 = np.array(data2)

In [5]:
arra2

array([4, 9, 8, 3, 5])

In [6]:
arr1.ndim # arr1 ning o'lchamini chiqaradi

1

In [7]:
arra2.ndim

1

In [8]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arra3 = np.array(data3)

In [9]:
arra3.ndim

2

In [10]:
data4 =[[[1,2,3,4],[8,9,6,7],[3,8,12,66]]]
arra4=np.array(data4)

In [11]:
arra4

array([[[ 1,  2,  3,  4],
        [ 8,  9,  6,  7],
        [ 3,  8, 12, 66]]])

In [12]:
arra4.shape#qator va ustunlar sonini ko'rsatadi(q,u)

(1, 3, 4)

In [13]:
arra4.size# arra4 ning elementlar soni

12

In [14]:
arra5 = np.zeros((3,4))
arra5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arra6 = np.ones((3,4))
arra6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arra7 = np.arange(1,10,2)#1 dan 10 gacha 2 qadam bilan massivga yuklaydi
arra7

array([1, 3, 5, 7, 9])

In [17]:
arra8 = np.arange(20)
arra8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
import numpy as np
dat1 = [1,2,5,36,72]
arra1 = np.array(dat1)
arra1

array([ 1,  2,  5, 36, 72])

In [21]:
def data1():
  arra2 = [r.randint(1,100) for _ in range(5)]

In [23]:
arra2

array([4, 9, 8, 3, 5])