In [1]:
import numpy as np

In [15]:
arr1 = np.array([1,2,3,4,5,6], dtype=np.float64)#bu float64 malumotlar turiga ega massiv bo'ladi
arr1

array([1., 2., 3., 4., 5., 6.])

In [3]:
arr2 = np.array([1,2,3], dtype=np.int32)#bu int32 malumotlar turiga ega massivni beradi
arr2

array([1, 2, 3], dtype=int32)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1,2,3,4])# int64
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

In [8]:
float_arr = arr.astype(np.float64)#float64 ga o'girdik
float_arr.dtype

dtype('float64')

In [9]:
data=np.array([3.4,5.7,6.3,2.9])#float64
data.dtype

dtype('float64')

In [10]:
int_data = data.astype(np.int64)
int_data.dtype

dtype('int64')