In [1]:
import numpy as np

In [2]:
arr = np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
arr[3:5]#kesadi

array([40, 50])

In [4]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
sliced_arr = arr[3:5]
sliced_arr[:]=0
sliced_arr

array([0, 0])

In [6]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [7]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
sliced_arr1 = arr1[:].copy()
sliced_arr1[:]=0
sliced_arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2d[1,1]

5

In [13]:
arr2d[2,2]

9

In [14]:
sl_arr2d=arr2d[2,1:]
sl_arr2d

array([8, 9])

In [15]:
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
arr3d[0][1,1]

4

In [17]:
arr3d[1][2, 1]

16

In [18]:
arr3d[2][0, :2]

array([18, 19])