In [1]:
import numpy as np

In [2]:
names = np.array(['Hasan','Husan','Mirazbek','Elyor','Hasan','Javohir','Elyor'])
names

array(['Hasan', 'Husan', 'Mirazbek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [3]:
data = np.random.randn(7,4)
data

array([[-1.85784894,  0.8344208 ,  0.12637677, -0.14011135],
       [ 0.34860813, -0.07327629, -2.61451023,  0.73665974],
       [-0.77952933,  1.29139822,  0.22699223, -1.58591722],
       [ 0.22070467,  0.6851187 , -0.53785491,  1.63985969],
       [-0.66709874,  0.72302508,  0.27096728, -1.48858321],
       [-0.89232119, -0.66001083, -2.14320022, -0.30010698],
       [-0.33203798, -0.66122057,  0.28812786,  0.78792727]])

In [4]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [5]:
data[names == 'Hasan']#Hasanga tegishli barcha malimotlarni ajratib olish

array([[-1.85784894,  0.8344208 ,  0.12637677, -0.14011135],
       [-0.66709874,  0.72302508,  0.27096728, -1.48858321]])

In [6]:
data[names == 'Elyor']

array([[ 0.22070467,  0.6851187 , -0.53785491,  1.63985969],
       [-0.33203798, -0.66122057,  0.28812786,  0.78792727]])

In [7]:
data[names == 'Javohir']

array([[-0.89232119, -0.66001083, -2.14320022, -0.30010698]])

In [8]:
data[names == 'Hasan',2:]

array([[ 0.12637677, -0.14011135],
       [ 0.27096728, -1.48858321]])

In [9]:
data[names != 'Javohir']#JAvohirdan boshqa barcha malumotni chiqaradi

array([[-1.85784894,  0.8344208 ,  0.12637677, -0.14011135],
       [ 0.34860813, -0.07327629, -2.61451023,  0.73665974],
       [-0.77952933,  1.29139822,  0.22699223, -1.58591722],
       [ 0.22070467,  0.6851187 , -0.53785491,  1.63985969],
       [-0.66709874,  0.72302508,  0.27096728, -1.48858321],
       [-0.33203798, -0.66122057,  0.28812786,  0.78792727]])

In [10]:
data[~(names == 'Hasan')]

array([[ 0.34860813, -0.07327629, -2.61451023,  0.73665974],
       [-0.77952933,  1.29139822,  0.22699223, -1.58591722],
       [ 0.22070467,  0.6851187 , -0.53785491,  1.63985969],
       [-0.89232119, -0.66001083, -2.14320022, -0.30010698],
       [-0.33203798, -0.66122057,  0.28812786,  0.78792727]])

In [11]:
data[0:2]

array([[-1.85784894,  0.8344208 ,  0.12637677, -0.14011135],
       [ 0.34860813, -0.07327629, -2.61451023,  0.73665974]])

In [12]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirazbek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[-1.85784894  0.8344208   0.12637677 -0.14011135]
 [ 0.34860813 -0.07327629 -2.61451023  0.73665974]
 [-0.77952933  1.29139822  0.22699223 -1.58591722]
 [ 0.22070467  0.6851187  -0.53785491  1.63985969]
 [-0.66709874  0.72302508  0.27096728 -1.48858321]
 [-0.89232119 -0.66001083 -2.14320022 -0.30010698]
 [-0.33203798 -0.66122057  0.28812786  0.78792727]]


In [13]:
mask = (names == 'Hasan') | (names == 'Husan')# "|" or (yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [14]:
data[mask]#Hasn va Husanlarga tegishli malumotlar

array([[-1.85784894,  0.8344208 ,  0.12637677, -0.14011135],
       [ 0.34860813, -0.07327629, -2.61451023,  0.73665974],
       [-0.66709874,  0.72302508,  0.27096728, -1.48858321]])

In [15]:
data

array([[-1.85784894,  0.8344208 ,  0.12637677, -0.14011135],
       [ 0.34860813, -0.07327629, -2.61451023,  0.73665974],
       [-0.77952933,  1.29139822,  0.22699223, -1.58591722],
       [ 0.22070467,  0.6851187 , -0.53785491,  1.63985969],
       [-0.66709874,  0.72302508,  0.27096728, -1.48858321],
       [-0.89232119, -0.66001083, -2.14320022, -0.30010698],
       [-0.33203798, -0.66122057,  0.28812786,  0.78792727]])

In [16]:
data[data<0] = 0
data

array([[0.        , 0.8344208 , 0.12637677, 0.        ],
       [0.34860813, 0.        , 0.        , 0.73665974],
       [0.        , 1.29139822, 0.22699223, 0.        ],
       [0.22070467, 0.6851187 , 0.        , 1.63985969],
       [0.        , 0.72302508, 0.27096728, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.28812786, 0.78792727]])