In [1]:
import numpy as np

In [2]:


A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
A.T# A massivning Trasnpose ko'rinishi ni beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [4]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
A.swapaxes(1,0)#A massivning Trasport ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [6]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
np.dot(A,A.T)#AA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])