In [2]:
import numpy as np

In [3]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(a)#a**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.square(a)#a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
np.exp(a)#a expanetni chiqaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
np.log(a[1:])# a logarifni hisoblaydi (loge)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
arr = np.random.randn(6)
arr

array([ 0.49567762,  0.89379432, -1.29909273,  0.85579456,  0.69035074,
       -0.28202977])

In [22]:
c,v=np.modf(arr)

In [23]:
print(c)
print(v)

[ 0.49567762  0.89379432 -0.29909273  0.85579456  0.69035074 -0.28202977]
[ 0.  0. -1.  0.  0. -0.]


In [25]:
np.sign(arr)#arr ishoralarini (-1 va 1) ko;rinishida qaytaradi

array([ 1.,  1., -1.,  1.,  1., -1.])

In [26]:
np.isnan(arr)

array([False, False, False, False, False, False])

In [27]:
arr[0]=np.NaN

In [28]:
arr

array([        nan,  0.89379432, -1.29909273,  0.85579456,  0.69035074,
       -0.28202977])

In [29]:
np.isnan(arr)

array([ True, False, False, False, False, False])

Ikta qiymat qabul qilv=uvchi funksiyalar

In [30]:
#2ta massiv
arr1 = np.random.randn(6)
arr2 = np.random.randn(6)

In [32]:
arr1

array([-1.15187493,  0.08753616,  3.67251407,  1.27426619,  2.11345746,
        0.55877018])

In [33]:
arr2

array([ 0.31928646, -0.12386016, -0.49682564, -0.22336114,  1.25851422,
        0.52244283])

In [34]:
np.add(arr1,arr2)#arr1 va arr2 ni qo'shadi

array([-0.83258847, -0.036324  ,  3.17568843,  1.05090506,  3.37197168,
        1.08121301])

In [35]:
arr1+arr2

array([-0.83258847, -0.036324  ,  3.17568843,  1.05090506,  3.37197168,
        1.08121301])