In [2]:
import numpy as np

In [4]:
x=np.array([1.1,1.2,1.3,1.4,1.5])#x
y=np.array([2.1,2.2,2.3,2.4,2.5])#y

In [5]:
#Shart
c=np.array([True,False,True,True,False])

In [7]:
r=np.where(c,x,y)#C tru bo'lsa x elemen aks holda y element
r

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
arr=np.random.randn(4,4)#(4,4)o'lchamdagi massiv
arr

array([[ 1.52558274, -1.07907026,  0.28961109,  0.82443774],
       [ 0.12404718,  1.15077581, -1.92814257, -0.29491425],
       [ 0.95477546, -0.06842568, -0.4375376 , -0.06189459],
       [ 1.68429987, -0.42002691, -1.57697547,  1.17024356]])

In [10]:
#Where
resu = np.where(arr<0,-2,2)#arr<0 kichik bo'lsa -2 ga musbatni 2 ga almashtirish
resu

array([[ 2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [ 2, -2, -2, -2],
       [ 2, -2, -2,  2]])

In [18]:
rt=np.where(arr>0.1 ,arr,0)
rt

array([[1.52558274, 0.        , 0.28961109, 0.82443774],
       [0.12404718, 1.15077581, 0.        , 0.        ],
       [0.95477546, 0.        , 0.        , 0.        ],
       [1.68429987, 0.        , 0.        , 1.17024356]])